elems:

  - src: ^((xmonad)\.hs)$
    dst: ~/.<2>/<1>
    only: f?xmonad

  - src:  ^xmobar/((?!.*\.zsh).+)$
    dst:  <%= var!(:"xmobar.base_dir") %>/<1>
    only: f?xmonad && f?xmobar

  - src:   ^xmobar/(.+\.zsh)$
    dst:   <%= xdg_config_home(:xmobar) %>/<1>
    perms: 755
    only:  f?xmonad && f?xmobar

  - src:   ^(taffybar\.hs)$
    dst:   <%= xdg_config_home(:taffybar) %>/<1>
    only:  f?xmonad && f?taffybar


# vim: set filetype=eruby.yaml :
