elems:

  - src:  ^(xmonad)/(.+\.hs)$
    dst:  ~/.<1>/<2>
    only: f?xmonad

  - src:  ^taffybar/(.+\.hs)$
    dst:  <%= xdg_config_home :taffybar %>/<1>
    only: f?xmonad && f?taffybar

  - src:   ^(taffybar\.hs)$
    dst:   <%= xdg_config_home(:taffybar) %>/<1>
    only:  f?xmonad && f?taffybar


# vim: set filetype=eruby.yaml :
