elems:

  - src:  ^(xmonad)/(.+)$
    dst:  ~/.<1>/<2>
    only: f?xmonad

  - src:  ^taffybar/(.+)$
    dst:  <%= get_var! "taffybar.dir" %>/<1>
    only: f?xmonad && f?taffybar


# vim: set filetype=eruby.yaml :
